openapi: 3.0.0
paths:
  /calculator:
    post:
      operationId: CalculatorController_calculate
      parameters:
        - name: arithmetic-value
          required: true
          in: header
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationRequestBody'
      responses:
        '201':
          description: ''
  /auth/token:
    get:
      operationId: AuthController_getToken
      parameters: []
      responses:
        '200':
          description: ''
info:
  title: Calculator API
  description: API for performing arithmetic operations
  version: '1.0'
  contact: {}
tags: []
servers:
  - url: http://localhost:3000
components:
  schemas:
    CalculationRequestBody:
      type: object
      properties:
        num1:
          type: number
        num2:
          type: number
      required:
        - num1
        - num2
